@baseUrl =  http://localhost:3000/api/artists

# User API

# @name Getall
GET {{baseUrl}}/admin?field=deleted&value=true
###

# @name Getall
PATCH {{baseUrl}}/change-status/6540b6226c605c44082d40a9
###

# @name Search
GET {{baseUrl}}/search?q=nguyen quang dung

###
# @name GetbyId
GET {{baseUrl}}/tran-thanh

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/beecine-afb84.appspot.com/o/images%2F1694868829450_daodien2.jpg?alt=media&token=0a0e6920-c9a7-4769-8016-4d7f472e640d",
    "name":{
        "vi": "Lan Ngọc",
        "en": "Lan Ngoc"
    },
    "roles": {
        "vi": ["Đạo diễn" ],
        "en": ["Director" ]
    },
    "bio": {
        "vi": "Mô tả đạo diễn",
        "en": "Director bio"
    },
    "country":"65329673197a79f48d54f502"
}

###

# 
# 
# @name Update
PUT {{baseUrl}}/update/653297bca608544e51e1112a
Content-Type: application/json


{
   "roles": ["Diễn viên"]
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c9ee2f999d05165d828c68

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83
