@baseUrl =  http://localhost:3000/api/artists

# User API

# @name Getall
GET {{baseUrl}}


###
# @name GetbyId
GET {{baseUrl}}/64c9ee2f999d05165d828c68

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "avatarUrl":"Demo",
    "name":"Demo 12",
    "role":"Demo",
    "bio":"Demo",
    "country":"Demo"
}

###

# @name Update
PUT {{baseUrl}}/update/64c290ee173cda17c307a2fa
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c9ee2f999d05165d828c68

###