@baseUrl =  http://localhost:3000/api/auth

# Auth API

# @name GetUsers
GET http://localhost:3000/api/users

###

# @name SignOut
@cookie = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTJmZTczOTRmM2Q0NTQyZjZkNWU1YjEiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTY5NzY0MDAxNSwiZXhwIjoxNzI5MTc2MDE1fQ.jFR5R4MJpzD3D_YbVF86zumQIv8uw29xHoSVFFxntKk
POST {{baseUrl}}/sign-out
Cookie: {{cookie}}

###

# @name SignIn
POST {{baseUrl}}/sign-in
Content-Type: application/json

{
  "userId" : "652fe7394f3d4542f6d5e5b1"
}

###

# @name SignInWithGoogle
POST {{baseUrl}}/sign-in-with-google
Content-Type: application/json

{
  "email" : "voquocan99@gmail.com"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTE5NmFjNDk5NDg4ZWU5NjNjNWRjMDkiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2OTc2MjI3NDAsImV4cCI6MTY5NzYyMjc3MH0.zQcM2sCRMnj04Fw_kn8lfX7ssWmYzNKFMO1Y-agzCfM

# @name GetProfile
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}

###

# @name RefreshToken
POST {{baseUrl}}/refresh-token
Content-Type: application/json

{
  "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTJmZWY3Mzc2ZWVhMGI3OGNlYTQzYTgiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTY5NzY5OTk5MSwiZXhwIjoxNzI5MjM1OTkxfQ.7l9N_NEWWH4gRoLjpwIynriOC8XFNNvDliuI-CD9fAY"
}
###

# @name SignInWithGoogle
POST {{baseUrl}}/sign-in-with-google


###

# @name SignUp
POST {{baseUrl}}/sign-up

###




