@baseUrl =  http://localhost:3000/api/banners

# User API

# @name Getall
GET {{baseUrl}}/admin?filter=null


###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###

# 65329d4fd207a51351bc1cea
# 65329db7d207a51351bc1ced
# 65329df3d207a51351bc1cf0
# 65329e2cd207a51351bc1cf3

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
  "title":{
    "vi": "Phần phim mới nhất của lý tiểu long",
    "en": "The latest movie of Bruce Lee"
  },
  "description":{
    "vi": "Đây là một bộ phim siêu anh hùng của Marvel cực kỳ hấp dẫn bạn không thể bỏ qua hãy nhấn vào xem ngay",
    "en": "This is a super hero movie of Marvel extremely attractive you can not ignore click to watch now"
  },
  "logoUrl":"https://cdn.marvel.com/content/1x/mulogo_lob_log_eye_01_1.png",
  "imageUrl":"https://cdn.marvel.com/content/1x/msm_0608_com_mas_dsk_01.jpg",
  "link":"#"
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json

[
  {
  "imageUrl": "https://example.com/banners/banner1.jpg",
  "order": 1,
  "link": "https://example.com/page1"
},

{
  "imageUrl": "https://example.com/banners/banner2.jpg",
  "order": 2,
  "link": "https://example.com/page2"  
},

{
  "imageUrl": "https://example.com/banners/banner3.jpg",
  "order": 3,
  "link": "https://example.com/page3"
}
]

###

# @name Update
PUT {{baseUrl}}/update/64c290ee173cda17c307a2fa
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c290ee173cda17c307a2fa

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "6532a1d42a33272e0c8d48d8",
        "6532a1da2a33272e0c8d48da",
        "6532a1dd2a33272e0c8d48dc",
        "6532a1e02a33272e0c8d48de"
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/6532a1e02a33272e0c8d48de
#  "6532a1d42a33272e0c8d48d8",
#         "6532a1da2a33272e0c8d48da",
#         "6532a1dd2a33272e0c8d48dc",
#         "6532a1e02a33272e0c8d48de"