@baseUrl =  http://localhost:3000/api/bills

# User API

# @name Getall
GET {{baseUrl}}


###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
   "userId": "5f9b9b3b1c9d440000d9d0a1",
   "subscriptionId": "5f9b9b3b1c9d440000d9d0a1",
   "endDate":"2020-11-01",
   "startDate":"2020-11-01",
   "total": 100000,
   "paymentMethod": "cash"
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json


###

# @name Update
PUT {{baseUrl}}/update/5f9b9b3b1c9d440000d9d0a1
Content-Type: application/json

{
   "duration": "yearly"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/5f9b9b3b1c9d440000d9d0a1

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83
