@baseUrl =  http://localhost:3000/api/bills

# User API

# @name Getall
GET {{baseUrl}}


###
# @name GetbyId
GET {{baseUrl}}/652a5cfa921f5083708545b7

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
   "userId": "6525328cbc23bb7dad9e3cc4",
   "subscriptionId": "652016e6c58e982ae6377690"
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json


###

# @name Update
PUT {{baseUrl}}/update/5f9b9b3b1c9d440000d9d0a1
Content-Type: application/json

{
   "duration": "yearly"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/5f9b9b3b1c9d440000d9d0a1

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83
