@baseUrl =  http://localhost:3000/api/comments

# User API

# @name Getall
GET {{baseUrl}} 


###
# @name GetbyId
GET {{baseUrl}}/64c4c69b8f02e1f31bdc33af

###
# @name ToggleLike
GET {{baseUrl}}/like-comment

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
  "userId": "64c290ee173cda17c307a2fa",
  "movieId": "64c290ee173cda17c307a2fa",
  "content": "demo"
}

###
# @name CreateReply
POST {{baseUrl}}/store-reply
Content-Type: application/json

{
  "commentId": "6522accd37fe2aaaa93bc362",
  "userId": "64c290ee173cda17c307a2fa",
  "movieId": "64c290ee173cda17c307a2fa",
  "content": "demo reply 123"
}

###
# @name Update
PUT {{baseUrl}}/update/6522accd37fe2aaaa93bc362
Content-Type: application/json

{
  "userId": "64c290ee173cda17c307a2fa",
  "movieId": "64c290ee173cda17c307a2fa",
  "content": "demo 12"
}
###
# @name UpdateReply
PUT {{baseUrl}}/update-reply
Content-Type: application/json

{
  "replyId": "6522aefa5283b93724ff2840",
  "commentId": "6522accd37fe2aaaa93bc362",
  "userId": "64c290ee173cda17c307a2fa",
  "movieId": "64c290ee173cda17c307a2fa",
  "content": "test 0987654"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c4c69b8f02e1f31bdc33af

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83
