@baseUrl =  http://localhost:3000/api/comments

# User API

# @name Getall
GET {{baseUrl}}/all

###
# @name Getall by id
GET {{baseUrl}}/movie/64c290ee173cda17c307a2fa


###
# @name GetbyId
GET {{baseUrl}}/6522accd37fe2aaaa93bc362

###
# @name ToggleLike commentId, userId, action
GET {{baseUrl}}/like-comment?action=dislike&commentId=6522accd37fe2aaaa93bc362&userId=64c290ee173cda17c307a2fa

###
###
# @name ToggleLike commentId, replyId, userId, action
GET {{baseUrl}}/like-reply?action=dislike&replyId=6522aef25283b93724ff283c&commentId=6522accd37fe2aaaa93bc362&userId=64c290ee173cda17c307a2fa

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
  "userId": "64c290ee173cda17c307a2fa",
  "movieId": "64c290ee173cda17c307a2fa",
  "content": "demo"
}

###
# @name CreateReply
POST {{baseUrl}}/store-reply
Content-Type: application/json

{
  "commentId": "6522accd37fe2aaaa93bc362",
  "userId": "64c290ee173cda17c307a2fa",
  "movieId": "64c290ee173cda17c307a2fa",
  "content": "demo reply 123"
}

###
# @name Update
PUT {{baseUrl}}/update/6522accd37fe2aaaa93bc362
Content-Type: application/json

{
  "userId": "64c290ee173cda17c307a2fa",
  "movieId": "64c290ee173cda17c307a2fa",
  "content": "demo 12345"
}
###
# @name UpdateReply
PUT {{baseUrl}}/update-reply
Content-Type: application/json

{
  "replyId": "6522aefa5283b93724ff2840",
  "commentId": "6522accd37fe2aaaa93bc362",
  "userId": "64c290ee173cda17c307a2fa",
  "movieId": "64c290ee173cda17c307a2fa",
  "content": "test 0987654"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c4c69b8f02e1f31bdc33af
###

# @name Delete Reply
DELETE {{baseUrl}}/delete-reply?commentId=6522accd37fe2aaaa93bc362&replyId=6522aef25283b93724ff283c

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/6522accd37fe2aaaa93bc362

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83
