@baseUrl = http://localhost:3000/api

# User API

# @name Search
GET {{baseUrl}}/stats
###
# @name Search
GET {{baseUrl}}/top-movie?period=week
###
# @name Search
GET {{baseUrl}}/top-genre?period=week
###
# @name Search
GET {{baseUrl}}/top-user?period=
###
# @name Search
GET {{baseUrl}}/profit?period=year  
