@baseUrl =  http://localhost:3000/api/countries

# User API

# @name Getall
GET {{baseUrl}} 


###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name": "Phim ca nhạc"
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json

[
 {
    "name": "Philippines",
    "code": "PH",
    "language": "Filipino, English",
    "currency": "Philippine peso",
    "telephone": "+63"
  },
  {
    "name": "Myanmar",
    "code": "MM",
    "language": "Burmese",
    "currency": "Burmese kyat",
    "telephone": "+95"
  },
  {
    "name": "Cambodia",
    "code": "KH",
    "language": "Khmer",
    "currency": "Cambodian riel",
    "telephone": "+855"
  },
  {
    "name": "Laos",
    "code": "LA",
    "language": "Lao",
    "currency": "Lao kip",
    "telephone": "+856"
  },
  {
    "name": "Australia",
    "code": "AU",
    "language": "English",
    "currency": "Australian dollar",
    "telephone": "+61"
  },
  {
    "name": "Canada",
    "code": "CA",
    "language": "English, French",
    "currency": "Canadian dollar",
    "telephone": "+1"
  },
  {
    "name": "Germany",
    "code": "DE",
    "language": "German",
    "currency": "Euro",
    "telephone": "+49"
  },
  {
    "name": "France",
    "code": "FR",
    "language": "French",
    "currency": "Euro",
    "telephone": "+33"
  }
]

###

# @name Update
PUT {{baseUrl}}/update/64c290ee173cda17c307a2fa
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c290ee173cda17c307a2fa

###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83


