@baseUrl =  http://localhost:3000/api/episodes

# User API

# @name Getall
GET {{baseUrl}} 


###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
  "movieId": "64c290ee173cda17c307a2fa",
  "thumbnailUrl": "https://www.youtube.com/watch?v=1roy4o4tqQM",
  "title": "demo 1",
  "description" : "demo",
  "airDate": "2020-11-01",
  "duration": 120
}
###

# @name Create
POST {{baseUrl}}/store-single
Content-Type: application/json

{
  "movieId": "64c290ee173cda17c307a2fa",
  "thumbnailUrl": "https://www.youtube.com/watch?v=1roy4o4tqQM",
  "title": "demo 1",
  "videoUrl": "https://www.youtube.com/watch?v=1roy4o4tqQM"
}



###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json


###

# @name Update
PUT {{baseUrl}}/update/64c290ee173cda17c307a2fa
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64ca0980a202ffce3e50fd45

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83
