@baseUrl =  http://localhost:3000/api/episodes

# User API

# @name Getall
GET {{baseUrl}}


###
# @name GetbyId
GET {{baseUrl}}/6520152dc58e982ae637764e

###
# @name GetbyMovieId
GET {{baseUrl}}/movie/652cb9de21d691c2871d3e70?season=2

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
  "movieId": "64c290ee173cda17c307a2fa",
   "title": {
    "vi": "về nhà đi con",
    "en": "Come Home Love: Lo and Behold"
  },
  "description" : {
    "vi": "Mô tả",
    "en": "Description"
  },
  "season": 1,
  "number": 2,
  "duration": 50,
  "imageUrl": {
    "vi": "https://firebasestorage.googleapis.com/v0/b/beecine-afb84.appspot.com/o/images%2F1696601493098_phim-bo-gia-tran-thanh-viet-nam.jpg?alt=media&token=9d2fb741-4285-4a68-a93c-d7f149f16f55&_gl=1*f5rqej*_ga*NjQ1NzkxNjY2LjE2ODg2NTQ2Nzk.*_ga_CW55HF8NVT*MTY5NzgxMzQzMC43MC4xLjE2OTc4MTUyODMuNDMuMC4w",
    "en": "https://firebasestorage.googleapis.com/v0/b/beecine-afb84.appspot.com/o/images%2F1696601493098_phim-bo-gia-tran-thanh-viet-nam.jpg?alt=media&token=9d2fb741-4285-4a68-a93c-d7f149f16f55&_gl=1*f5rqej*_ga*NjQ1NzkxNjY2LjE2ODg2NTQ2Nzk.*_ga_CW55HF8NVT*MTY5NzgxMzQzMC43MC4xLjE2OTc4MTUyODMuNDMuMC4w"
  },
  "videoUrl": "IkaP0KJWTsQ"
}
###

# @name Create
POST {{baseUrl}}/store-single
Content-Type: application/json

{
  "movieId": "64c290ee173cda17c307a2fa",
  "thumbnailUrl": "https://www.youtube.com/watch?v=1roy4o4tqQM",
  "title": "demo 1",
  "videoUrl": "https://www.youtube.com/watch?v=1roy4o4tqQM"
}



###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json


###

# @name Update
PUT {{baseUrl}}/update/64c290ee173cda17c307a2fa
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64ca0980a202ffce3e50fd45

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83
