@baseUrl =  http://localhost:3000/api/genres

# User API

# @name Getall
GET {{baseUrl}}


###
# @name GetHome
GET {{baseUrl}}/home

###
# @name ChangeBoolean
PATCH {{baseUrl}}/change-boolean/653294e56f4dee8b53be372e?field=isChildrent


###
# @name GetbyId
GET {{baseUrl}}/hanh-dong

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name": {
        "vi": "Cổ trang",
        "en": "Historical"
    },
    "isHome": true
}

###

# @name Update
PUT {{baseUrl}}/update/653294e56f4dee8b53be372e
Content-Type: application/json

{
    "isHome": true,
    "order": 5
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64cb7f54f921928736b32b80

###

# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/653281d76d75071e6963f7cc
