@baseUrl =  http://localhost:3000/api/profiles

# User API

# @name Getall
GET {{baseUrl}} 


###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name": "Phim ca nhạc",
    "avatarUrl": "https://example.com/avatars/avatar1.jpg"
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json


###

# @name Update
PUT {{baseUrl}}/update/64cba147782f6dd5332a968a
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64cba1a0782f6dd5332a968e

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cba147782f6dd5332a968a
###

# @name ForceDelete
DELETE {{baseUrl}}/force/64cba1a0782f6dd5332a968e
