@baseUrl =  http://localhost:3000/api/profiles

# User API

# @name Getall
GET {{baseUrl}} 


###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name": "Võ Quốc An 1",
    "imageUrl": "https://firebasestorage.googleapis.com/v0/b/beecine-afb84.appspot.com/o/images%2F1694771101896_daodien2.jpg?alt=media&token=544f67c8-4d28-47d8-ba98-0dcddb45905e",
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json


###

# @name Update
PUT {{baseUrl}}/update/64cba147782f6dd5332a968a
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64cba1a0782f6dd5332a968e

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cba147782f6dd5332a968a
###

# @name ForceDelete
DELETE {{baseUrl}}/force/64cba1a0782f6dd5332a968e
