@baseUrl =  http://localhost:3000/api/seo

# User API

# @name Getall
GET {{baseUrl}}/all
###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "title": "Phim ảnh",
    "description": "Phim ảnh",
    "keywords": ["Phim ảnh"],
    "image": "https://www.google.com.vn/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
    "canonical": "https://www.google.com.vn/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
    "robots": "Phim ảnh"
}

###

# 
# 
# @name Update
PUT {{baseUrl}}/update/655e0ac08fdb389d4ad83d5f
Content-Type: application/json


{
    "title": "Phim ảnh 1",
    "description": "Phim ảnh 1"
}
