@baseUrl =  http://localhost:3000/api/subscriptions

# User API

# @name Getall
GET {{baseUrl}} 


###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name": "Gói Cơ bản",
    "price": 100000,
    "duration": 30
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json


###

# @name Update
PUT {{baseUrl}}/update/64c290ee173cda17c307a2fa
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c290ee173cda17c307a2fa

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64cb7f5af921928736b32b83
