@baseUrl =  http://localhost:3000/api/users

# User API

# @name Getall
GET {{baseUrl}}


###
# @name Getall Uid
GET {{baseUrl}}/uid/LU3SFZETKzPKq2WizNzL8d7tv713


###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
  "name": "demo12334567",
  "email": "voquocan99@gmail.com",
  "uid": "LU3SFZETKzPKq2WizNzL8d7tv713"
}
###

# @name Create gg
POST {{baseUrl}}/store-with-google
Content-Type: application/json

{
  "name": "Qan ưeret",
  "email": "voquocan99@gmail.com",
  "uid": "LU3SFZETKzPKq2WizNzL8d7tv713"
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json

[
]

###

# @name Update
PUT {{baseUrl}}/update/6523c4ddc715d289a5532bf2
Content-Type: application/json

{
  "imageUrl": "https://example.com/banners/banner1.jpg",
  "name": "quoc an",
  "email": "demo00092345673@gmail.com",
  "uid": "1234",
  "permissions": ["ADD", "EDIT", "DELETE"]
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c290ee173cda17c307a2fa

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/65252d9dbc23bb7dad9e3cb6
