@baseUrl =  http://localhost:3000/api/users

# User API

# @name Getall
GET {{baseUrl}}

###
# @name GetbyId
GET {{baseUrl}}/64c290ee173cda17c307a2fa

###
# @name GetFavorite
GET {{baseUrl}}/favorite-movies/6533cdd989ac42618a10014b?page=1&limit=1
###
# @name GetWatched
GET {{baseUrl}}/watched-list/6533cdd989ac42618a10014b?
###
# @name GetWatchLater
GET {{baseUrl}}/watch-later-list/6533cdd989ac42618a10014b
###

# @name Create favorite
POST {{baseUrl}}/favorite
Content-Type: application/json

# 65329db7d207a51351bc1ced
# 65329d4fd207a51351bc1cea
{
  "userId": "6533cdd989ac42618a10014b",
  "movieId": "65329d4fd207a51351bc1cea"
}
###

# @name Create history
POST {{baseUrl}}/watched
Content-Type: application/json

{
  "userId": "6533cdd989ac42618a10014b",
  "movieId": "65329d4fd207a51351bc1cea",
  "minutes": "89"
}
###

# @name Create history
POST {{baseUrl}}/watch-later
Content-Type: application/json

{
  "userId": "6533cdd989ac42618a10014b",
  "movieId": "65329d4fd207a51351bc1cea"
}

###
# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
  "name": "demo12334567",
  "email": "voquocan99@gmail.com",
  "uid": "LU3SFZETKzPKq2WizNzL8d7tv713"
}
###

# @name Create gg
POST {{baseUrl}}/store-with-google
Content-Type: application/json

{
  "name": "Qan ưeret",
  "email": "voquocan99@gmail.com",
  "uid": "LU3SFZETKzPKq2WizNzL8d7tv713"
}

###
# @name CreateMany
POST {{baseUrl}}/store-many
Content-Type: application/json

[
]

###

# @name Update
PUT {{baseUrl}}/update/6523c4ddc715d289a5532bf2
Content-Type: application/json

{
  "imageUrl": "https://example.com/banners/banner1.jpg",
  "name": "quoc an",
  "email": "demo00092345673@gmail.com",
  "uid": "1234",
  "permissions": ["ADD", "EDIT", "DELETE"]
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64c290ee173cda17c307a2fa

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64cb7f54f921928736b32b80

###
# @name ForceDelete
DELETE {{baseUrl}}/force/65252d9dbc23bb7dad9e3cb6
